FROM python:3.10-alpine

WORKDIR /opt/app

COPY backend/ ./
RUN python -m pip install --no-cache -r requirements.txt


EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]